# Generated by Django 3.2.9 on 2022-02-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loveplanet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientModel',
            new_name='MemberModel',
        ),
    ]
